@api = "https://localhost:5001"
@productApi = "http://localhost:5002"
;
### Get list of product types
GET http://localhost:5002/product_types

### Get list of products
GET http://localhost:5002/products/828519

### Calculate insurance for a product
POST http://localhost:5000/api/insurance/product
Content-Type: application/json

{
    "ProductId": 828519
}

### Calculate insurance for an order
POST http://localhost:5000/api/insurance/order
Content-Type: application/json

{
    "OrderItems": [
        {
            "ProductId": 858421,
            "Quantity": 10
        },
        {
            "ProductId": 836676,
            "Quantity": 2
        },
        {
            "ProductId": 828519,
            "Quantity": 5
        }
    ]
}


### Calculate insurance for an order
PUT http://localhost:5000/api/insurance/surcharge
Content-Type: application/json

[
    {
        "ProductTypeId": 32,
        "Surcharge": 0.8
    },
    {
        "ProductTypeId": 3,
        "Surcharge": 0.2
    }
]